import { env } from "@/lib/env";
import type { ExtractionProvider } from "@/lib/extraction/providers/provider";
import { structuredDocumentJsonSchema, structuredDocumentSchema } from "@/lib/extraction/schema";

function extractOutputText(payload: Record<string, unknown>) {
  const directText = payload.output_text;

  if (typeof directText === "string" && directText.length > 0) {
    return directText;
  }

  const output = payload.output;

  if (Array.isArray(output)) {
    for (const item of output) {
      if (!item || typeof item !== "object") {
        continue;
      }

      const content = (item as { content?: unknown }).content;

      if (!Array.isArray(content)) {
        continue;
      }

      for (const entry of content) {
        if (!entry || typeof entry !== "object") {
          continue;
        }

        const text = (entry as { text?: unknown }).text;

        if (typeof text === "string" && text.length > 0) {
          return text;
        }
      }
    }
  }

  return null;
}

export class OpenAiExtractionProvider implements ExtractionProvider {
  readonly kind = "OPENAI" as const;

  async extractStructuredDocument(input: {
    rawText: string;
    fileName: string;
    mimeType: string;
  }) {
    if (!env.OPENAI_API_KEY) {
      throw new Error("OPENAI_API_KEY is required for the OpenAI extraction provider.");
    }

    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${env.OPENAI_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: env.OPENAI_MODEL,
        input: [
          {
            role: "system",
            content: [
              {
                type: "input_text",
                text: [
                  "Extract structured fields from internal business intake and compliance documents.",
                  "Return best-effort values, preserve uncertainty in notes, and never invent missing values.",
                  "If a field is absent, return null. Confidence must be between 0 and 1.",
                ].join(" "),
              },
            ],
          },
          {
            role: "user",
            content: [
              {
                type: "input_text",
                text: [
                  `File name: ${input.fileName}`,
                  `MIME type: ${input.mimeType}`,
                  "Transcript:",
                  input.rawText,
                ].join("\n"),
              },
            ],
          },
        ],
        text: {
          format: {
            type: "json_schema",
            name: "structured_document",
            strict: true,
            schema: structuredDocumentJsonSchema,
          },
        },
      }),
      cache: "no-store",
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`OpenAI extraction failed (${response.status}): ${errorBody}`);
    }

    const payload = (await response.json()) as Record<string, unknown>;
    const outputText = extractOutputText(payload);

    if (!outputText) {
      throw new Error("OpenAI extraction returned no structured output text.");
    }

    return {
      provider: this.kind,
      modelName: env.OPENAI_MODEL,
      document: structuredDocumentSchema.parse(JSON.parse(outputText)),
      notes: ["Structured extraction was generated by the OpenAI Responses API."],
    };
  }
}
