import { getDemoFixtureByFilename } from "@/lib/demo/fixtures";
import type { OcrAdapter } from "@/lib/extraction/ocr/types";

export class MockOcrAdapter implements OcrAdapter {
  readonly name = "mock-ocr";

  async extractText(input: { filePath: string; originalName: string }) {
    const fixture = getDemoFixtureByFilename(input.originalName);

    if (fixture) {
      return {
        text: fixture.rawText,
        confidence: fixture.slug === "suspicious-review" ? 0.68 : 0.88,
        notes: [
          "Mock OCR adapter was used because no external OCR provider is configured.",
          `Fixture match resolved from ${fixture.filename}.`,
        ],
      };
    }

    return {
      text: [
        "OCR fallback summary",
        `Filename: ${input.originalName}`,
        "No live OCR provider is configured in this environment.",
        "The mock adapter returned a placeholder transcript so the pipeline can stay runnable locally.",
      ].join("\n"),
      confidence: 0.42,
      notes: [
        "OCR output is placeholder content generated by the mock adapter.",
        "Configure a live OCR provider or upload one of the bundled demo fixtures for richer extraction.",
      ],
    };
  }
}
